In [40]:
import pandas as pd 
import tensorflow as tf 
i = 0

In [41]:
fbref_data = pd.read_csv("FPLFullDataset202122.csv")

In [42]:
fbref_data

,Unnamed: 0,Date,Day,Round,Venue,Result,Squad,Opponent,Start,Pos,...,Cmp,Att,Cmp%,PrgP,Carries,PrgC,Att.1,Succ,name,season
0,0,2018-08-12,Sun,Matchweek 1,Away,W 2–0,Manchester City,Arsenal,Y,GK,...,33.0,46.0,71.7,0.0,27.0,0.0,0.0,0.0,Ederson,2018/2019
1,1,2018-08-19,Sun,Matchweek 2,Home,W 6–1,Manchester City,Huddersfield,Y,GK,...,22.0,26.0,84.6,0.0,16.0,0.0,0.0,0.0,Ederson,2018/2019
2,2,2018-08-25,Sat,Matchweek 3,Away,D 1–1,Manchester City,Wolves,Y,GK,...,22.0,22.0,100.0,0.0,13.0,0.0,0.0,0.0,Ederson,2018/2019
3,3,2018-09-01,Sat,Matchweek 4,Home,W 2–1,Manchester City,Newcastle Utd,Y,GK,...,21.0,23.0,91.3,0.0,15.0,0.0,0.0,0.0,Ederson,2018/2019
4,4,2018-09-15,Sat,Matchweek 5,Home,W 3–0,Manchester City,Fulham,Y,GK,...,23.0,23.0,100.0,0.0,16.0,0.0,0.0,0.0,Ederson,2018/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62892,54249,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,Y,CB,...,22.0,27.0,81.5,0.0,13.0,0.0,1.0,1.0,James Bree,2022/2023
62893,54275,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,RB,...,6.0,8.0,75.0,0.0,3.0,0.0,3.0,2.0,Valentino Livramento,2022/2023
62894,54275,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,RW,...,6.0,8.0,75.0,0.0,3.0,0.0,3.0,2.0,Valentino Livramento,2022/2023
62895,54277,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,LM,...,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0,Dominic Ballard,2022/2023
62896,54277,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,FW,...,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0,Dominic Ballard,2022/2023

In [43]:
fbref_data.columns

Index(['Unnamed: 0', 'Date', 'Day', 'Round', 'Venue', 'Result', 'Squad',
       'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh',
       'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG',
       'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
       'Att.1', 'Succ', 'name', 'season'],
      dtype='object')

In [44]:
fbref_data.drop('Unnamed: 0', axis='columns')

,Date,Day,Round,Venue,Result,Squad,Opponent,Start,Pos,Min,...,Cmp,Att,Cmp%,PrgP,Carries,PrgC,Att.1,Succ,name,season
0,2018-08-12,Sun,Matchweek 1,Away,W 2–0,Manchester City,Arsenal,Y,GK,90.0,...,33.0,46.0,71.7,0.0,27.0,0.0,0.0,0.0,Ederson,2018/2019
1,2018-08-19,Sun,Matchweek 2,Home,W 6–1,Manchester City,Huddersfield,Y,GK,90.0,...,22.0,26.0,84.6,0.0,16.0,0.0,0.0,0.0,Ederson,2018/2019
2,2018-08-25,Sat,Matchweek 3,Away,D 1–1,Manchester City,Wolves,Y,GK,90.0,...,22.0,22.0,100.0,0.0,13.0,0.0,0.0,0.0,Ederson,2018/2019
3,2018-09-01,Sat,Matchweek 4,Home,W 2–1,Manchester City,Newcastle Utd,Y,GK,90.0,...,21.0,23.0,91.3,0.0,15.0,0.0,0.0,0.0,Ederson,2018/2019
4,2018-09-15,Sat,Matchweek 5,Home,W 3–0,Manchester City,Fulham,Y,GK,90.0,...,23.0,23.0,100.0,0.0,16.0,0.0,0.0,0.0,Ederson,2018/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62892,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,Y,CB,90.0,...,22.0,27.0,81.5,0.0,13.0,0.0,1.0,1.0,James Bree,2022/2023
62893,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,RB,14.0,...,6.0,8.0,75.0,0.0,3.0,0.0,3.0,2.0,Valentino Livramento,2022/2023
62894,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,RW,14.0,...,6.0,8.0,75.0,0.0,3.0,0.0,3.0,2.0,Valentino Livramento,2022/2023
62895,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,LM,5.0,...,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0,Dominic Ballard,2022/2023
62896,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,FW,5.0,...,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0,Dominic Ballard,2022/2023

In [45]:
ordered_fbref_data = fbref_data[['name', 'season', 'Date', 'Day', 'Round', 'Venue', 'Result', 'Squad',
       'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh',
       'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG',
       'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
       'Att.1', 'Succ']]

In [46]:
ordered_fbref_data

,name,season,Date,Day,Round,Venue,Result,Squad,Opponent,Start,...,SCA,GCA,Cmp,Att,Cmp%,PrgP,Carries,PrgC,Att.1,Succ
0,Ederson,2018/2019,2018-08-12,Sun,Matchweek 1,Away,W 2–0,Manchester City,Arsenal,Y,...,0.0,0.0,33.0,46.0,71.7,0.0,27.0,0.0,0.0,0.0
1,Ederson,2018/2019,2018-08-19,Sun,Matchweek 2,Home,W 6–1,Manchester City,Huddersfield,Y,...,1.0,1.0,22.0,26.0,84.6,0.0,16.0,0.0,0.0,0.0
2,Ederson,2018/2019,2018-08-25,Sat,Matchweek 3,Away,D 1–1,Manchester City,Wolves,Y,...,0.0,0.0,22.0,22.0,100.0,0.0,13.0,0.0,0.0,0.0
3,Ederson,2018/2019,2018-09-01,Sat,Matchweek 4,Home,W 2–1,Manchester City,Newcastle Utd,Y,...,0.0,0.0,21.0,23.0,91.3,0.0,15.0,0.0,0.0,0.0
4,Ederson,2018/2019,2018-09-15,Sat,Matchweek 5,Home,W 3–0,Manchester City,Fulham,Y,...,2.0,0.0,23.0,23.0,100.0,0.0,16.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62892,James Bree,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,Y,...,0.0,0.0,22.0,27.0,81.5,0.0,13.0,0.0,1.0,1.0
62893,Valentino Livramento,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,0.0,0.0,6.0,8.0,75.0,0.0,3.0,0.0,3.0,2.0
62894,Valentino Livramento,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,0.0,0.0,6.0,8.0,75.0,0.0,3.0,0.0,3.0,2.0
62895,Dominic Ballard,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,0.0,0.0,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0
62896,Dominic Ballard,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,0.0,0.0,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0

In [47]:
ordered_fbref_data['Pos'].unique()

array(['GK', 'CB', 'LB', 'RW', 'RM', 'DM', 'LW', 'FW', 'RB', 'CM', 'LM',
       'AM', 'WB'], dtype=object)

In [48]:
FW = ordered_fbref_data[ordered_fbref_data['Pos'] == "FW"]

In [49]:
FW['CrdY']

101      0.0
102      0.0
103      0.0
104      0.0
105      0.0
        ...
62848    0.0
62885    0.0
62887    0.0
62890    0.0
62896    0.0
Name: CrdY, Length: 8548, dtype: float64

In [50]:
FW.columns

Index(['name', 'season', 'Date', 'Day', 'Round', 'Venue', 'Result', 'Squad',
       'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh',
       'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG',
       'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
       'Att.1', 'Succ'],
      dtype='object')

In [51]:

FW['Xp2'] = (FW['Gls'] * 5) + ( FW['Ast'] * 3)  + 1 - (FW['CrdY']) # FPL Scoring System
FW['Xp'] = (FW['npxG'] * 5) + ( FW['xAG'] * 3)  + 1 - (FW['CrdY']) # FPL Scoring System

In [52]:
FW.loc[FW['Min'] > 60, 'Xp'] += 1 #adding a + 1 to players who have played >60 minutes

In [53]:
FW.loc[FW['Min'] > 60, 'Xp2'] += 1 #adding a + 1 to players who have played >60 minutes

In [54]:
train_data  = FW 
train_data.columns[ train_data.isna().any().tolist()]  #Get all the columns with NAN values

Index(['Cmp%'], dtype='object')

In [55]:
FW.columns

Index(['name', 'season', 'Date', 'Day', 'Round', 'Venue', 'Result', 'Squad',
       'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh',
       'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG',
       'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
       'Att.1', 'Succ', 'Xp2', 'Xp'],
      dtype='object')

In [56]:
train_data  = FW[ [  'Day', 'Round', 'Venue', 'Result',
                 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh',
                   'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG',
                   'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
                   'Att.1', 'Succ', 'Xp', 'Xp2'] ]

In [57]:
train_data['Round'] = train_data['Round'].str.replace('Matchweek ', '').astype(int)

In [58]:
categorical_columns = train_data.select_dtypes(include=['object'])  # Select only categorical columns
unique_counts = categorical_columns.nunique()
unique_counts

Day        7
Venue      2
Result    49
Start      3
Pos        1
dtype: int64

In [59]:
train_data.columns

Index(['Day', 'Round', 'Venue', 'Result', 'Start', 'Pos', 'Min', 'Gls', 'Ast',
       'PK', 'PKatt', 'Sh', 'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int',
       'Blocks', 'xG', 'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%',
       'PrgP', 'Carries', 'PrgC', 'Att.1', 'Succ', 'Xp', 'Xp2'],
      dtype='object')

In [60]:
train_data  = train_data.drop(['Result', 'Pos'], axis='columns')

In [61]:
train_data_encoded = pd.get_dummies(train_data, columns=['Day', 'Venue','Start' ])

In [62]:
train_data_encoded

,Round,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,...,Day_Sat,Day_Sun,Day_Thu,Day_Tue,Day_Wed,Venue_Away,Venue_Home,Start_N,Start_Y,Start_Y*
101,1,78.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,...,0,1,0,0,0,1,0,0,1,0
102,2,75.0,3.0,0.0,0.0,0.0,9.0,4.0,0.0,0.0,...,0,1,0,0,0,0,1,0,1,0
103,3,90.0,0.0,0.0,0.0,0.0,4.0,1.0,0.0,0.0,...,1,0,0,0,0,1,0,0,1,0
104,4,90.0,0.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0,...,1,0,0,0,0,0,1,0,1,0
105,5,53.0,0.0,1.0,0.0,0.0,5.0,1.0,0.0,0.0,...,1,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62848,33,90.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,1,0,0,0,1,0,1,0
62885,11,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,1,0,0
62887,20,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,0,0,0,1,0,1,0,0
62890,27,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,1,0,1,0,0
62896,38,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,1,0,0

In [63]:
train_data_encoded_imputed = train_data_encoded.fillna(train_data_encoded.mean())

In [64]:
train_data_encoded_imputed.columns[train_data_encoded_imputed.isna().any().tolist()]

Index([], dtype='object')

In [65]:
target = train_data_encoded_imputed['Xp']
target2 = train_data_encoded_imputed['Xp2']

In [66]:
train_data_encoded_imputed.columns

Index(['Round', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh', 'SoT', 'CrdY',
       'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG', 'xAG', 'SCA',
       'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC', 'Att.1', 'Succ',
       'Xp', 'Xp2', 'Day_Fri', 'Day_Mon', 'Day_Sat', 'Day_Sun', 'Day_Thu',
       'Day_Tue', 'Day_Wed', 'Venue_Away', 'Venue_Home', 'Start_N', 'Start_Y',
       'Start_Y*'],
      dtype='object')

In [67]:
X = train_data_encoded_imputed[['Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ' , 'Gls', 'Ast']]

In [68]:
X

,Min,Sh,SoT,Touches,Tkl,Int,Blocks,xG,npxG,xAG,...,Cmp,Att,Cmp%,PrgP,Carries,PrgC,Att.1,Succ,Gls,Ast
101,78.0,3.0,1.0,32.0,1.0,1.0,1.0,0.6,0.6,0.1,...,18.0,22.0,81.8,3.0,26.0,2.0,1.0,0.0,0.0,0.0
102,75.0,9.0,4.0,43.0,0.0,0.0,2.0,1.4,1.4,0.0,...,18.0,22.0,81.8,2.0,30.0,2.0,4.0,2.0,3.0,0.0
103,90.0,4.0,1.0,36.0,1.0,0.0,0.0,0.3,0.3,0.1,...,24.0,24.0,100.0,2.0,27.0,1.0,2.0,2.0,0.0,0.0
104,90.0,4.0,0.0,49.0,0.0,1.0,1.0,0.2,0.2,0.6,...,33.0,36.0,91.7,3.0,40.0,7.0,5.0,3.0,0.0,1.0
105,53.0,5.0,1.0,19.0,0.0,0.0,0.0,0.4,0.4,0.9,...,9.0,11.0,81.8,1.0,8.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62848,90.0,1.0,0.0,33.0,0.0,0.0,0.0,0.1,0.1,0.0,...,18.0,24.0,75.0,4.0,22.0,1.0,2.0,1.0,0.0,0.0
62885,17.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,4.0,50.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
62887,6.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,3.0,66.7,0.0,3.0,0.0,1.0,0.0,0.0,0.0
62890,15.0,0.0,0.0,9.0,0.0,0.0,1.0,0.0,0.0,0.0,...,3.0,4.0,75.0,0.0,5.0,1.0,1.0,0.0,0.0,0.0
62896,5.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0,0.0,0.0

<h3> Model Testing </h3>

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, target, test_size=0.3, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, target2, test_size=0.3, random_state=42)

In [70]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print('-------------------')
print("X_train shape:", X_train2.shape)
print("X_test shape:", X_test2.shape)
print("y_train shape:", y_train2.shape)
print("y_test shape:", y_test2.shape)

X_train shape: (5983, 22)
X_test shape: (2565, 22)
y_train shape: (5983,)
y_test shape: (2565,)
-------------------
X_train shape: (5983, 22)
X_test shape: (2565, 22)
y_train shape: (5983,)
y_test shape: (2565,)

In [71]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Creating a Random Forest Regressor
regressor = RandomForestRegressor(random_state=42)
regressor2 = RandomForestRegressor(random_state= 42)
# Train the regressor on the training data
regressor.fit(X_train, y_train)
regressor2.fit(X_train2, y_train2)
# Make predictions on the test data
y_pred = regressor.predict(X_test)
y_pred2 = regressor2.predict(X_test2)
# Evaluate the regressor using a regression metric (e.g., Mean Squared Error)
mse = mean_squared_error(y_test, y_pred)
mse2 = mean_squared_error(y_test2, y_pred2 )
print("Mean Squared Error:", mse)
print("Second Mean Squared Error: ", mse2)

Mean Squared Error: 0.10194598535845784
Second Mean Squared Error:  0.1150777486354776

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
y_train

In [ ]:
y_pred

In [ ]:
y_test

In [ ]:
y_pred2

In [ ]:
y_pred

from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

# Create a Random Forest Regressor
regressor = RandomForestRegressor(random_state=42)
scores = cross_val_score(regressor, X, target, cv=5, scoring='neg_mean_squared_error')
rmse_scores = (-scores)**0.5
for fold, rmse in enumerate(rmse_scores, start=1):
    print(f"Fold {fold}: RMSE = {rmse:.4f}")
mean_rmse = rmse_scores.mean()
print(f"Mean RMSE across all folds: {mean_rmse:.4f}")

In [ ]:
FW['Xp'].describe()

import matplotlib.pyplot as plt
import seaborn as sns

# Histogram to visualize the distribution of Xp values
plt.figure(figsize=(8, 6))
sns.histplot(FW['Xp'], bins=20, kde=True)
plt.xlabel('Xp (Expected Points)')
plt.ylabel('Frequency')
plt.title('Distribution of Xp')
plt.show()

# Box plot to identify outliers and quartiles
plt.figure(figsize=(8, 6))
sns.boxplot(x=FW['Xp'])
plt.xlabel('Xp (Expected Points)')
plt.title('Box Plot of Xp')
plt.show()

# Scatter plot to explore the relationship between Xp and another variable (e.g., Goals)
plt.figure(figsize=(8, 6))
sns.scatterplot(data=FW, x='Xp', y='Gls')
plt.xlabel('Xp (Expected Points)')
plt.ylabel('Goals')
plt.title('Scatter Plot: Xp vs. Goals')
plt.show()

In [ ]:
import pandas as pd

# Group the data by "Team" and calculate the average for "Xp" and "Goals"
team_stats = FW.groupby('name')[['Xp', 'Gls', 'xAG']].mean().reset_index()
# Print or display the resulting DataFrame
print(team_stats.sort_values(['Xp'], ascending=False))

In [ ]:
# Group the data by "Team" and calculate the average for "Xp" and "Goals"
team_stats = FW.groupby('Squad')[['Xp', 'Gls', 'xAG']].mean().reset_index()
# Print or display the resulting DataFrame
print(team_stats)

<h3> Getting 22/23 Data from FBref site </h3>

In [ ]:
# Getting agrregated data from last 3 gameweeks, we will make a prediction on the fourth gameweek based on this

In [3]:
from FBrefScraper import * #Created a utils package that will help me out in getting the data 
import warnings
warnings.filterwarnings('ignore')

In [2]:
team_year = "2022-2023"
team_links = get_team_links(team_year)
player_data = get_player_data(team_links)

<Response [200]>

KeyboardInterrupt:

In [ ]:
team_links

In [ ]:
player_data

<Response [200]>

In [4]:
squad_names

['Manchester-City-',
 'Arsenal-',
 'Manchester-United-',
 'Newcastle-United-',
 'Liverpool-',
 'Brighton-and-Hove-Albion-',
 'Aston-Villa-',
 'Tottenham-Hotspur-',
 'Brentford-',
 'Fulham-',
 'Crystal-Palace-',
 'Chelsea-',
 'Wolverhampton-Wanderers-',
 'West-Ham-United-',
 'Bournemouth-',
 'Nottingham-Forest-',
 'Everton-',
 'Leicester-City-',
 'Leeds-United-',
 'Southampton-']

In [15]:
team_years = ["2018-2019","2019-2020", "2021-2022", "2022-2023"] 
all_season_df = [] 
for team_year in team_years:
    team_links = get_team_links(team_year)
    squad_names = get_squads_name(team_links)
    pd_all_team_stats  = get_team_statistics(team_year, squad_names)
    all_season_df.append( pd.concat(pd_all_team_stats) )
    print(pd.concat(pd_all_team_stats))

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
          Date   Time         Round  Day Venue Result  GF  GA        Opponent  \
0   2018-08-12  16:00   Matchweek 1  Sun  Away      W   2   0         Arsenal
1   2018-08-19  13:30   Matchweek 2  Sun  Home      W   6   1    Huddersfield
2   2018-08-25  12:30   Matchweek 3  Sat  Away      D   1   1          Wolves
3   2018-09-01  17:30   Matchweek 4  Sat  Home      W   2   1   Newcastle Utd
4   2018-09-15  15:00   Matchweek 5  Sat  Home      W   3   0          Fulham
..         ...    ...           ...  ...   ...    ...  ..  ..             ...
33  2019-04-20  12:30  Matchweek 35  Sat  Home      W   1   0       Tottenham
34  2019-04-24  20:00  Matchweek 31  Wed  Away      W   2   0  Manchester Utd
35  2019-04-28  14:05  Matchweek 36  Sun  Away      W   1   0         Burnley
36  2019-05-06  20:00  Matchweek 37  Mon  Home      W   1   0  Leicester City
37  2019-05-12  15:00  Matchweek 38  Sun  Away      W   4   1        Brighton

     xG  xGA  Poss  Attendance          Captain Formation          Referee  \
0   1.7  0.5    58       59934      Fernandinho   4-2-3-1   Michael Oliver
1   4.2  0.7    76       54021  Vincent Kompany   3-1-4-2   Andre Marriner
2   1.6  1.0    71       31322  Vincent Kompany     4-3-3  Martin Atkinson
3   2.0  0.5    78       53946      David Silva   4-1-3-2     Kevin Friend
4   4.8  0.4    64       53307      David Silva     4-3-3   Stuart Attwell
..  ...  ...   ...         ...              ...       ...              ...
33  1.9  1.0    61       54489    Sergio Agüero     4-3-3   Michael Oliver
34  0.5  0.5    63       74431  Vincent Kompany     4-3-3   Andre Marriner
35  2.5  0.1    69       21605  Vincent Kompany     4-3-3     Paul Tierney
36  1.0  0.5    61       54506  Vincent Kompany     4-3-3        Mike Dean
37  1.6  0.5    75       30662  Vincent Kompany   4-4-1-1   Michael Oliver

    Match Report  Notes           team_name     season
0   Match Report    NaN    Manchester City   2018/2019
1   Match Report    NaN    Manchester City   2018/2019
2   Match Report    NaN    Manchester City   2018/2019
3   Match Report    NaN    Manchester City   2018/2019
4   Match Report    NaN    Manchester City   2018/2019
..           ...    ...                 ...        ...
33  Match Report    NaN  Huddersfield Town   2018/2019
34  Match Report    NaN  Huddersfield Town   2018/2019
35  Match Report    NaN  Huddersfield Town   2018/2019
36  Match Report    NaN  Huddersfield Town   2018/2019
37  Match Report    NaN  Huddersfield Town   2018/2019

[760 rows x 20 columns]
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
          Date   Time         Round  Day Venue Result  GF  GA       Opponent  \
0   2019-08-10  12:30   Matchweek 1  Sat  Away      W   5   0       West Ham
1   2019-08-17  17:30   Matchweek 2  Sat  Home      D   2   2      Tottenham
2   2019-08-25  14:00   Matchweek 3  Sun  Away      W   3   1    Bournemouth
3   2019-08-31  15:00   Matchweek 4  Sat  Home      W   4   0       Brighton
4   2019-09-14  17:30   Matchweek 5  Sat  Away      L   2   3   Norwich City
..         ...    ...           ...  ...   ...    ...  ..  ..            ...
33  2020-07-08  18:00  Matchweek 34  Wed  Home      W   5   0  Newcastle Utd
34  2020-07-11  20:00  Matchweek 35  Sat  Away      W   5   0       Brighton
35  2020-07-15  18:00  Matchweek 36  Wed  Home      W   2   1    Bournemouth
36  2020-07-21  18:00  Matchweek 37  Tue  Away      W   4   0        Watford
37  2020-07-26  16:00  Matchweek 38  Sun  Home      W   5   0   Norwich City

     xG  xGA  Poss  Attendance          Captain Formation         Referee  \
0   3.2  1.1    57     59870.0      David Silva     4-3-3       Mike Dean
1   2.9  0.1    55     54503.0  Kevin De Bruyne   4-2-3-1  Michael Oliver
2   3.0  2.2    74     10486.0      David Silva     4-3-3  Andre Marriner
3   1.9  0.9    53     54386.0      David Silva     4-3-3   Jonathan Moss
4   2.3  1.5    68     27035.0      David Silva   4-2-3-1    Kevin Friend
..  ...  ...   ...         ...              ...       ...             ...
33  2.8  0.3    73         NaN      David Silva     4-3-3     Andy Madley
34  4.4  0.2    70         NaN  Kevin De Bruyne     4-3-3    Graham Scott
35  0.7  1.6    71         NaN      David Silva   4-2-3-1       Lee Mason
36  3.3  0.1    76         NaN  Kevin De Bruyne     4-3-3  Michael Oliver
37  3.2  1.0    73         NaN      David Silva     4-3-3    Craig Pawson

    Match Report  Notes      team_name     season
0   Match Report    NaN     Liverpool   2019/2020
1   Match Report    NaN     Liverpool   2019/2020
2   Match Report    NaN     Liverpool   2019/2020
3   Match Report    NaN     Liverpool   2019/2020
4   Match Report    NaN     Liverpool   2019/2020
..           ...    ...            ...        ...
33  Match Report    NaN  Norwich City   2019/2020
34  Match Report    NaN  Norwich City   2019/2020
35  Match Report    NaN  Norwich City   2019/2020
36  Match Report    NaN  Norwich City   2019/2020
37  Match Report    NaN  Norwich City   2019/2020

[760 rows x 20 columns]
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
          Date   Time         Round  Day Venue Result  GF  GA        Opponent  \
0   2021-08-15  16:30   Matchweek 1  Sun  Away      L   0   1       Tottenham
1   2021-08-21  15:00   Matchweek 2  Sat  Home      W   5   0    Norwich City
2   2021-08-28  12:30   Matchweek 3  Sat  Home      W   5   0         Arsenal
3   2021-09-11  15:00   Matchweek 4  Sat  Away      W   1   0  Leicester City
4   2021-09-18  15:00   Matchweek 5  Sat  Home      D   0   0     Southampton
..         ...    ...           ...  ...   ...    ...  ..  ..             ...
33  2022-04-30  17:30  Matchweek 35  Sat  Away      W   4   0    Leeds United
34  2022-05-08  16:30  Matchweek 36  Sun  Home      W   5   0   Newcastle Utd
35  2022-05-11  20:15  Matchweek 33  Wed  Away      W   5   1          Wolves
36  2022-05-15  14:00  Matchweek 37  Sun  Away      D   2   2        West Ham
37  2022-05-22  16:00  Matchweek 38  Sun  Home      W   3   2     Aston Villa

     xG  xGA  Poss  Attendance         Captain Formation          Referee  \
0   1.8  1.0    65       58262     Fernandinho     4-3-3   Anthony Taylor
1   2.6  0.1    67       51437  İlkay Gündoğan     4-3-3     Graham Scott
2   4.4  0.2    80       52276  İlkay Gündoğan     4-3-3  Martin Atkinson
3   2.8  0.6    61       32087  İlkay Gündoğan     4-3-3     Paul Tierney
4   1.0  0.4    64       52698     Fernandinho     4-3-3    Jonathan Moss
..  ...  ...   ...         ...             ...       ...              ...
33  2.4  1.3    58       35771  İlkay Gündoğan   4-2-3-1     Paul Tierney
34  3.1  0.8    71       53336  İlkay Gündoğan   4-2-3-1   Stuart Attwell
35  2.3  0.5    66       32000     Fernandinho   4-2-3-1  Martin Atkinson
36  2.4  1.1    78       59972     Fernandinho     4-3-3   Anthony Taylor
37  3.4  0.2    71       53395     Fernandinho     4-3-3   Michael Oliver

    Match Report  Notes         team_name     season
0   Match Report    NaN  Manchester City   2021/2022
1   Match Report    NaN  Manchester City   2021/2022
2   Match Report    NaN  Manchester City   2021/2022
3   Match Report    NaN  Manchester City   2021/2022
4   Match Report    NaN  Manchester City   2021/2022
..           ...    ...               ...        ...
33  Match Report    NaN     Norwich City   2021/2022
34  Match Report    NaN     Norwich City   2021/2022
35  Match Report    NaN     Norwich City   2021/2022
36  Match Report    NaN     Norwich City   2021/2022
37  Match Report    NaN     Norwich City   2021/2022

[760 rows x 20 columns]

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
          Date   Time         Round  Day Venue Result  GF  GA  \
0   2022-08-07  16:30   Matchweek 1  Sun  Away      W   2   0
1   2022-08-13  15:00   Matchweek 2  Sat  Home      W   4   0
2   2022-08-21  16:30   Matchweek 3  Sun  Away      D   3   3
3   2022-08-27  15:00   Matchweek 4  Sat  Home      W   4   2
4   2022-08-31  19:30   Matchweek 5  Wed  Home      W   6   0
..         ...    ...           ...  ...   ...    ...  ..  ..
33  2023-05-06  15:00  Matchweek 35  Sat  Home      W   2   1
34  2023-05-14  14:00  Matchweek 36  Sun  Away      W   3   0
35  2023-05-21  16:00  Matchweek 37  Sun  Home      W   1   0
36  2023-05-24  20:00  Matchweek 32  Wed  Away      D   1   1
37  2023-05-28  16:30  Matchweek 38  Sun  Away      L   0   1

           Opponent   xG  xGA  Poss  Attendance          Captain Formation  \
0          West Ham  2.2  0.5    75       62443   İlkay Gündoğan     4-3-3
1       Bournemouth  1.7  0.1    67       53453   İlkay Gündoğan   4-2-3-1
2     Newcastle Utd  2.1  1.8    69       52258   İlkay Gündoğan     4-3-3
3    Crystal Palace  2.2  0.1    74       53112  Kevin De Bruyne   4-2-3-1
4   Nott'ham Forest  3.3  0.7    74       53409   İlkay Gündoğan   4-2-3-1
..              ...  ...  ...   ...         ...              ...       ...
33     Leeds United  2.6  0.2    80       53406   İlkay Gündoğan   3-2-4-1
34          Everton  0.8  1.6    63       39376   İlkay Gündoğan   4-2-3-1
35          Chelsea  1.2  1.2    64       53490      Kyle Walker    3-4-3◆
36         Brighton  1.8  2.2    60       31388   İlkay Gündoğan     4-3-3
37        Brentford  1.6  1.3    65       17120      Kyle Walker   3-2-4-1

           Referee  Match Report  Notes         team_name     season
0   Michael Oliver  Match Report    NaN  Manchester City   2022/2023
1      David Coote  Match Report    NaN  Manchester City   2022/2023
2   Jarred Gillett  Match Report    NaN  Manchester City   2022/2023
3   Darren England  Match Report    NaN  Manchester City   2022/2023
4     Paul Tierney  Match Report    NaN  Manchester City   2022/2023
..             ...           ...    ...               ...        ...
33     Andy Madley  Match Report    NaN      Southampton   2022/2023
34  Anthony Taylor  Match Report    NaN      Southampton   2022/2023
35  Michael Oliver  Match Report    NaN      Southampton   2022/2023
36    Simon Hooper  Match Report    NaN      Southampton   2022/2023
37     John Brooks  Match Report    NaN      Southampton   2022/2023

[760 rows x 20 columns]

In [18]:
concatenated_df = pd.concat(all_season_df)

In [20]:
concatenated_df.to_csv("AllPLTeamsStats.csv")

In [23]:
player_stats = pd.read_csv("PL202223Season.csv")

In [24]:
player_stats = player_stats[player_stats['Pos'] !='On matchday squad, but did not play']

In [27]:
player_stats.columns

Index(['Unnamed: 0', 'Date', 'Day', 'Comp', 'Round', 'Venue', 'Result',
       'Squad', 'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt',
       'Sh', 'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'Match Report', 'name', 'season'],
      dtype='object')

In [28]:
player_stats = player_stats[['name', 'season',  'Date', 'Day', 'Comp', 'Round', 'Venue', 'Result',
       'Squad', 'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt',
       'Sh', 'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'Match Report']]

In [30]:
player_stats = player_stats[player_stats['Pos'] == 'MID']

In [31]:
player_stats

Empty DataFrame
Columns: [name, season, Date, Day, Comp, Round, Venue, Result, Squad, Opponent, Start, Pos, Min, Gls, Ast, PK, PKatt, Sh, SoT, CrdY, CrdR, Touches, Tkl, Int, Blocks, xG, npxG, xAG, SCA, GCA, Cmp, Att, Cmp%, PrgP, Carries, PrgC, Att.1, Succ, Match Report]
Index: []

[0 rows x 39 columns]

<h3> Cleaning the data a little bit before feeding it into the model </h3>

In [32]:
new_season  = pd.read_csv("FixedForwards.csv")

<p style="color: green;"> <bold> TODO:</bold> Fix the all_players_cleaned columns dataset to match the X.columns one, then do the analysis </p>

In [33]:
new_season

,Unnamed: 0,name,season,Date,Day,Comp,Round,Venue,Result,Squad,...,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost,element_type
0,0,Erling Haaland,2023/2024,2023-08-11,Fri,Premier League,Matchweek 1,Away,W 3–0,Manchester City,...,248.0,6,161,54.4,2,0,0,91.9,141,FWD
1,1,Erling Haaland,2023/2024,2023-08-19,Sat,Premier League,Matchweek 2,Home,W 1–0,Manchester City,...,248.0,6,161,54.4,2,0,0,91.9,141,FWD
2,2,Erling Haaland,2023/2024,2023-08-27,Sun,Premier League,Matchweek 3,Away,W 2–1,Manchester City,...,248.0,6,161,54.4,2,0,0,91.9,141,FWD
3,3,Erling Haaland,2023/2024,2023-09-02,Sat,Premier League,Matchweek 4,Home,W 5–1,Manchester City,...,248.0,6,161,54.4,2,0,0,91.9,141,FWD
4,4,Cody Gakpo,2023/2024,2023-08-27,Sun,Premier League,Matchweek 3,Away,W 2–1,Liverpool,...,21.0,0,18,7.1,0,0,0,3.7,73,FWD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,90,Lyle Foster,2023/2024,2023-09-02,Sat,Premier League,Matchweek 4,Home,L 2–5,Burnley,...,76.0,1,53,18.5,0,0,0,0.6,50,FWD
91,91,Zeki Amdouni,2023/2024,2023-08-11,Fri,Premier League,Matchweek 1,Home,L 0–3,Burnley,...,36.0,0,18,8.1,0,0,0,0.1,55,FWD
92,92,Zeki Amdouni,2023/2024,2023-08-27,Sun,Premier League,Matchweek 3,Home,L 1–3,Burnley,...,36.0,0,18,8.1,0,0,0,0.1,55,FWD
93,93,Zeki Amdouni,2023/2024,2023-09-02,Sat,Premier League,Matchweek 4,Home,L 2–5,Burnley,...,36.0,0,18,8.1,0,0,0,0.1,55,FWD
94,94,Jay Rodriguez,2023/2024,2023-08-27,Sun,Premier League,Matchweek 3,Home,L 1–3,Burnley,...,5.0,0,-3,0.1,0,0,0,0.2,54,FWD

In [34]:
new_season.drop(['Unnamed: 0'], axis='columns', inplace=True)

In [35]:
X.columns

NameError: name 'X' is not defined

In [36]:
new_season.rename(columns = {'element_type':'Pos'}, inplace = True)
new_season.columns

Index(['name', 'season', 'Date', 'Day', 'Comp', 'Round', 'Venue', 'Result',
       'Squad', 'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt',
       'Sh', 'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Att.1', 'Cmp%', 'PrgP',
       'Carries', 'PrgC', 'Att.2', 'Att.3', 'Succ', 'Match Report',
       'goals_scored', 'assists', 'total_points', 'minutes', 'goals_conceded',
       'creativity', 'influence', 'threat', 'bonus', 'bps', 'ict_index',
       'clean_sheets', 'red_cards', 'yellow_cards', 'selected_by_percent',
       'now_cost', 'Pos'],
      dtype='object')

In [37]:
new_season = new_season[['name', 'Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG',
       'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
       'Att.1' ,'Succ', 'Gls', 'Ast']]
column_mean = new_season['Cmp%'].mean()
# Fill NaN values in the specific column with the mean
new_season['Cmp%'].fillna(column_mean, inplace=True)
new_seasons = new_season.groupby('name').mean().reset_index()
names = new_seasons['name']
new_seasons = new_seasons[[ 'Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG',
       'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
       'Att.1' ,'Succ', 'Gls', 'Ast']]

In [38]:
print(new_seasons.columns)
print(X.columns)

Index(['Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG',
       'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
       'Att.1', 'Succ', 'Gls', 'Ast'],
      dtype='object')

NameError: name 'X' is not defined

In [39]:
Fpl_points = regressor.predict(new_seasons)
Fpl_points2 = regressor2.predict(new_seasons)

NameError: name 'regressor' is not defined

In [ ]:
new_seasons['Names'] = names

In [ ]:
new_seasons['Xp'] = Fpl_points
new_seasons['Xp2'] = Fpl_points2

In [ ]:
i = 5
new_seasons[['Names', 'Xp', 'Xp2']].to_csv(f"My {i}th FplPrediction for next gameweek.csv", index = False)