In [552]:
import pandas as pd 
import tensorflow as tf 
i = 0 
POSITION = "MIDFIELDERS"

In [553]:
fbref_data = pd.read_csv("FPLFullDataset202122.csv")

In [554]:
#fbref_data = fbref_data.drop(['Unnamed: 0'],    axis = 'columns'

Unnamed: 0      int64
Date           object
Day            object
Round          object
Venue          object
Result         object
Squad          object
Opponent       object
Start          object
Pos            object
Min           float64
Gls           float64
Ast           float64
PK            float64
PKatt         float64
Sh            float64
SoT           float64
CrdY          float64
CrdR          float64
Touches       float64
Tkl           float64
Int           float64
Blocks        float64
xG            float64
npxG          float64
xAG           float64
SCA           float64
GCA           float64
Cmp           float64
Att           float64
Cmp%          float64
PrgP          float64
Carries       float64
PrgC          float64
Att.1         float64
Succ          float64
name           object
season         object
dtype: object

In [555]:
df2.columns

Index(['Date', 'Time', 'Round', 'Day', 'Venue', 'Result', 'GF', 'GA',
       'Opponent', 'xG', 'xGA', 'Poss', 'Attendance', 'Captain', 'Formation',
       'Referee', 'Match Report', 'Notes', 'Squad', 'season'],
      dtype='object')

In [556]:
df2['Round'] = df2['Round'].str.strip()
df2['Squad'] = df2['Squad'].str.strip()
df2['season'] = df2['season'].str.strip() 
fbref_data['Round'] = fbref_data['Round'].str.strip()
fbref_data['Squad'] = fbref_data['Squad'].str.strip()
fbref_data['season'] = fbref_data['season'].str.strip()

In [557]:
fbref_data.dtypes

Unnamed: 0      int64
Date           object
Day            object
Round          object
Venue          object
Result         object
Squad          object
Opponent       object
Start          object
Pos            object
Min           float64
Gls           float64
Ast           float64
PK            float64
PKatt         float64
Sh            float64
SoT           float64
CrdY          float64
CrdR          float64
Touches       float64
Tkl           float64
Int           float64
Blocks        float64
xG            float64
npxG          float64
xAG           float64
SCA           float64
GCA           float64
Cmp           float64
Att           float64
Cmp%          float64
PrgP          float64
Carries       float64
PrgC          float64
Att.1         float64
Succ          float64
name           object
season         object
dtype: object

In [558]:
df2 = pd.read_csv("AllPLTeamsStats.csv")
df2 = df2.drop(['Unnamed: 0'], axis= 'columns') 
#fbref_data = fbref_data.drop(['Unnamed: 0 '], axis='columns')
df2['Round'] = df2['Round'].str.strip()
df2['Squad'] = df2['Squad'].str.strip()
df2['season'] = df2['season'].str.strip() 
fbref_data['Round'] = fbref_data['Round'].str.strip()
fbref_data['Squad'] = fbref_data['Squad'].str.strip()
fbref_data['season'] = fbref_data['season'].str.strip() 
#fbref_data = fbref.drop(['Unnamed: 0'], axis= 'columns') 
print(df2.columns)
print(fbref_data.columns )
final_data_withXGA = fbref_data.merge(df2, how='left', on =['Round', 'season', 'Squad'])

Index(['Date', 'Time', 'Round', 'Day', 'Venue', 'Result', 'GF', 'GA',
       'Opponent', 'xG', 'xGA', 'Poss', 'Attendance', 'Captain', 'Formation',
       'Referee', 'Match Report', 'Notes', 'Squad', 'season'],
      dtype='object')
Index(['Unnamed: 0', 'Date', 'Day', 'Round', 'Venue', 'Result', 'Squad',
       'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh',
       'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG',
       'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
       'Att.1', 'Succ', 'name', 'season'],
      dtype='object')

Unnamed: 0      int64
Date           object
Day            object
Round          object
Venue          object
Result         object
Squad          object
Opponent       object
Start          object
Pos            object
Min           float64
Gls           float64
Ast           float64
PK            float64
PKatt         float64
Sh            float64
SoT           float64
CrdY          float64
CrdR          float64
Touches       float64
Tkl           float64
Int           float64
Blocks        float64
xG            float64
npxG          float64
xAG           float64
SCA           float64
GCA           float64
Cmp           float64
Att           float64
Cmp%          float64
PrgP          float64
Carries       float64
PrgC          float64
Att.1         float64
Succ          float64
name           object
season         object
dtype: object
Date_x                  object
Time                    object
Round                   object
Day_x                   object
Venue_x                 object
                        ...
red_cards              float64
yellow_cards           float64
selected_by_percent    float64
now_cost               float64
element_type            object
Length: 73, dtype: object

In [575]:
#final_data_withXGA.to_csv('FinalDataWithXGA.csv')

In [561]:
ordered_fbref_data = final_data_withXGA[['name', 'season', 'Date_x', 'Day_x', 'Round', 'Venue_x', 'Result_x', 'Squad',
       'Opponent_x', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh',
       'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG_x', 'npxG',
       'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries', 'PrgC',
       'Att.1', 'Succ', 'xGA']]

In [562]:
ordered_fbref_data

,name,season,Date_x,Day_x,Round,Venue_x,Result_x,Squad,Opponent_x,Start,...,GCA,Cmp,Att,Cmp%,PrgP,Carries,PrgC,Att.1,Succ,xGA
0,Ederson,2018/2019,2018-08-12,Sun,Matchweek 1,Away,W 2–0,Manchester City,Arsenal,Y,...,0.0,33.0,46.0,71.7,0.0,27.0,0.0,0.0,0.0,0.5
1,Ederson,2018/2019,2018-08-19,Sun,Matchweek 2,Home,W 6–1,Manchester City,Huddersfield,Y,...,1.0,22.0,26.0,84.6,0.0,16.0,0.0,0.0,0.0,0.7
2,Ederson,2018/2019,2018-08-25,Sat,Matchweek 3,Away,D 1–1,Manchester City,Wolves,Y,...,0.0,22.0,22.0,100.0,0.0,13.0,0.0,0.0,0.0,1.0
3,Ederson,2018/2019,2018-09-01,Sat,Matchweek 4,Home,W 2–1,Manchester City,Newcastle Utd,Y,...,0.0,21.0,23.0,91.3,0.0,15.0,0.0,0.0,0.0,0.5
4,Ederson,2018/2019,2018-09-15,Sat,Matchweek 5,Home,W 3–0,Manchester City,Fulham,Y,...,0.0,23.0,23.0,100.0,0.0,16.0,0.0,0.0,0.0,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62892,James Bree,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,Y,...,0.0,22.0,27.0,81.5,0.0,13.0,0.0,1.0,1.0,1.3
62893,Valentino Livramento,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,0.0,6.0,8.0,75.0,0.0,3.0,0.0,3.0,2.0,1.3
62894,Valentino Livramento,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,0.0,6.0,8.0,75.0,0.0,3.0,0.0,3.0,2.0,1.3
62895,Dominic Ballard,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,0.0,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0,1.3
62896,Dominic Ballard,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,0.0,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0,1.3

In [563]:
ordered_fbref_data['Pos'].unique()

array(['GK', 'CB', 'LB', 'RW', 'RM', 'DM', 'LW', 'FW', 'RB', 'CM', 'LM',
       'AM', 'WB'], dtype=object)

In [564]:
MID = ordered_fbref_data[ (ordered_fbref_data['Pos'] == "RW") | (ordered_fbref_data['Pos'] == "RM") | (ordered_fbref_data['Pos'] == "DM") | (ordered_fbref_data['Pos'] == "LW") | (ordered_fbref_data['Pos'] == "LM") | (ordered_fbref_data['Pos'] == "CM") | (ordered_fbref_data['Pos'] == "AM")]

In [565]:
MID['Xp'] = (MID['npxG'] * 5) + ( MID['xAG'] * 3)  + 1 - (MID['CrdY']) # FPL Scoring System

In [566]:
MID.loc[MID['Min'] > 60, 'Xp'] += 1 #adding a + 1 to players who have played >60 minutes
MID.loc[(MID['xGA'] < 1) & (MID['Min'] > 60) , 'Xp'] += 1 #Adding a + 1 to players who have less than a 1 XG and has played more than 60 minutes

In [567]:
train_data_encoded_imputed = MID.fillna(MID.mean())

In [568]:
train_data_encoded_imputed

,name,season,Date_x,Day_x,Round,Venue_x,Result_x,Squad,Opponent_x,Start,...,Cmp,Att,Cmp%,PrgP,Carries,PrgC,Att.1,Succ,xGA,Xp
72,Bernardo Silva,2018/2019,2018-08-25,Sat,Matchweek 3,Away,D 1–1,Manchester City,Wolves,Y,...,23.0,33.0,69.7,1.0,27.0,2.0,3.0,3.0,1.0,2.5
73,Bernardo Silva,2018/2019,2018-09-15,Sat,Matchweek 5,Home,W 3–0,Manchester City,Fulham,Y,...,53.0,61.0,86.9,7.0,56.0,5.0,3.0,2.0,0.4,7.9
74,Bernardo Silva,2018/2019,2018-09-22,Sat,Matchweek 6,Away,W 5–0,Manchester City,Cardiff City,Y,...,53.0,64.0,82.8,6.0,53.0,4.0,1.0,0.0,0.1,4.7
75,Bernardo Silva,2018/2019,2018-09-29,Sat,Matchweek 7,Home,W 2–0,Manchester City,Brighton,Y,...,46.0,50.0,92.0,5.0,43.0,3.0,1.0,1.0,0.2,4.2
76,Bernardo Silva,2018/2019,2018-10-07,Sun,Matchweek 8,Away,D 0–0,Manchester City,Liverpool,Y,...,51.0,60.0,85.0,4.0,50.0,4.0,1.0,0.0,0.4,2.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62886,Sekou Mara,2022/2023,2022-10-16,Sun,Matchweek 11,Home,D 1–1,Southampton,West Ham,N,...,2.0,4.0,50.0,0.0,2.0,0.0,0.0,0.0,2.1,1.0
62888,Sekou Mara,2022/2023,2023-01-14,Sat,Matchweek 20,Away,W 2–1,Southampton,Everton,N,...,2.0,3.0,66.7,0.0,3.0,0.0,1.0,0.0,1.7,1.0
62889,Sekou Mara,2022/2023,2023-03-12,Sun,Matchweek 27,Away,D 0–0,Southampton,Manchester Utd,N,...,3.0,4.0,75.0,0.0,5.0,1.0,1.0,0.0,0.2,1.0
62894,Valentino Livramento,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,6.0,8.0,75.0,0.0,3.0,0.0,3.0,2.0,1.3,1.0
62895,Dominic Ballard,2022/2023,2023-05-28,Sun,Matchweek 38,Home,D 4–4,Southampton,Liverpool,N,...,2.0,3.0,66.7,0.0,4.0,0.0,1.0,0.0,1.3,1.0

In [569]:
target = train_data_encoded_imputed['Xp']

In [570]:
X = train_data_encoded_imputed[['name' , 'Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG_x',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'xGA']]

In [571]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, target, test_size=0.3, random_state=42)

In [572]:

X_test_name = X_test['name']
X_test = X_test[[ 'Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG_x',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'xGA']]

X_train = X_train[[ 'Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG_x',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'xGA']]

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (21561, 21)
X_test shape: (9241, 21)
y_train shape: (21561,)
y_test shape: (9241,)

In [573]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Create a Random Forest Regressor
regressor = RandomForestRegressor(random_state=42)
# Train the regressor on the training data
regressor.fit(X_train, y_train)
# Make predictions on the test data
y_pred = regressor.predict(X_test)
# Evaluate the regressor using a regression metric (e.g., Mean Squared Error)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.1022174612094734

<h2> Testing on current season</h2>

<p> Getting current season
   data </p>

In [574]:
from FBrefScraper import * #Created a utils package that will help me out in getting the data 
import warnings
warnings.filterwarnings('ignore')

In [377]:
all_season_df =[]
team_year = '2023-2024'
team_links = get_team_links(team_year)
squad_names = get_squads_name(team_links)
pd_all_team_stats  = get_team_statistics(team_year, squad_names)
all_season_df.append( pd.concat(pd_all_team_stats) )
print(pd.concat(pd_all_team_stats))

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
          Date   Time         Round  Day Venue Result   GF   GA  \
0   2023-08-11  20:00   Matchweek 1  Fri  Away      W  3.0  0.0
1   2023-08-19  20:00   Matchweek 2  Sat  Home      W  1.0  0.0
2   2023-08-27  14:00   Matchweek 3  Sun  Away      W  2.0  1.0
3   2023-09-02  15:00   Matchweek 4  Sat  Home      W  5.0  1.0
4   2023-09-16  15:00   Matchweek 5  Sat  Away    NaN  NaN  NaN
..         ...    ...           ...  ...   ...    ...  ...  ...
33  2024-04-20    NaN  Matchweek 34  Sat  Away    NaN  NaN  NaN
34  2024-04-27    NaN  Matchweek 35  Sat  Away    NaN  NaN  NaN
35  2024-05-04    NaN  Matchweek 36  Sat  Home    NaN  NaN  NaN
36  2024-05-11    NaN  Matchweek 37  Sat  Away    NaN  NaN  NaN
37  2024-05-19    NaN  Matchweek 38  Sun  Home    NaN  NaN  NaN

           Opponent   xG  xGA  Poss  Attendance          Captain Formation  \
0           Burnley  1.9  0.3  65.0     21572.0  Kevin De Bruyne   4-2-3-1
1     Newcastle Utd  1.0  0.3  59.0         NaN      Kyle Walker   4-2-3-1
2     Sheffield Utd  3.5  0.7  79.0     31336.0      Kyle Walker   4-2-3-1
3            Fulham  2.2  1.4  68.0     52899.0      Kyle Walker   4-2-3-1
4          West Ham  NaN  NaN   NaN         NaN              NaN       NaN
..              ...  ...  ...   ...         ...              ...       ...
33        Tottenham  NaN  NaN   NaN         NaN              NaN       NaN
34  Nott'ham Forest  NaN  NaN   NaN         NaN              NaN       NaN
35           Wolves  NaN  NaN   NaN         NaN              NaN       NaN
36           Fulham  NaN  NaN   NaN         NaN              NaN       NaN
37         West Ham  NaN  NaN   NaN         NaN              NaN       NaN

           Referee  Match Report Notes         team_name     season
0     Craig Pawson  Match Report   NaN  Manchester City   2023/2024
1     Robert Jones  Match Report   NaN  Manchester City   2023/2024
2   Jarred Gillett  Match Report   NaN  Manchester City   2023/2024
3   Michael Oliver  Match Report   NaN  Manchester City   2023/2024
4              NaN  Head-to-Head   NaN  Manchester City   2023/2024
..             ...           ...   ...               ...        ...
33             NaN  Head-to-Head   NaN          Burnley   2023/2024
34             NaN  Head-to-Head   NaN          Burnley   2023/2024
35             NaN  Head-to-Head   NaN          Burnley   2023/2024
36             NaN  Head-to-Head   NaN          Burnley   2023/2024
37             NaN  Head-to-Head   NaN          Burnley   2023/2024

[760 rows x 20 columns]

In [577]:
XGA_stats = pd.concat (pd_all_team_stats)

In [578]:
XGA_stats

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,xG,xGA,Poss,Attendance,Captain,Formation,Referee,Match Report,Notes,team_name,season
0,2023-08-11,20:00,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,1.9,0.3,65.0,21572.0,Kevin De Bruyne,4-2-3-1,Craig Pawson,Match Report,NaN,Manchester City,2023/2024
1,2023-08-19,20:00,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,1.0,0.3,59.0,NaN,Kyle Walker,4-2-3-1,Robert Jones,Match Report,NaN,Manchester City,2023/2024
2,2023-08-27,14:00,Matchweek 3,Sun,Away,W,2.0,1.0,Sheffield Utd,3.5,0.7,79.0,31336.0,Kyle Walker,4-2-3-1,Jarred Gillett,Match Report,NaN,Manchester City,2023/2024
3,2023-09-02,15:00,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,2.2,1.4,68.0,52899.0,Kyle Walker,4-2-3-1,Michael Oliver,Match Report,NaN,Manchester City,2023/2024
4,2023-09-16,15:00,Matchweek 5,Sat,Away,NaN,NaN,NaN,West Ham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN,Manchester City,2023/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,2024-04-20,NaN,Matchweek 34,Sat,Away,NaN,NaN,NaN,Tottenham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN,Burnley,2023/2024
34,2024-04-27,NaN,Matchweek 35,Sat,Away,NaN,NaN,NaN,Nott'ham Forest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN,Burnley,2023/2024
35,2024-05-04,NaN,Matchweek 36,Sat,Home,NaN,NaN,NaN,Wolves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN,Burnley,2023/2024
36,2024-05-11,NaN,Matchweek 37,Sat,Away,NaN,NaN,NaN,Fulham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN,Burnley,2023/2024
37,2024-05-19,NaN,Matchweek 38,Sun,Home,NaN,NaN,NaN,West Ham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN,Burnley,2023/2024

In [579]:
 XGA_stats =  XGA_stats[ (XGA_stats['Round'] == "Matchweek 1") | (XGA_stats['Round'] == "Matchweek 2") | (XGA_stats['Round'] == "Matchweek 3")| (XGA_stats['Round'] == "Matchweek 4")]

In [580]:
XGA_stats

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,xG,xGA,Poss,Attendance,Captain,Formation,Referee,Match Report,Notes,team_name,season
0,2023-08-11,20:00,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,1.9,0.3,65.0,21572.0,Kevin De Bruyne,4-2-3-1,Craig Pawson,Match Report,NaN,Manchester City,2023/2024
1,2023-08-19,20:00,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,1.0,0.3,59.0,NaN,Kyle Walker,4-2-3-1,Robert Jones,Match Report,NaN,Manchester City,2023/2024
2,2023-08-27,14:00,Matchweek 3,Sun,Away,W,2.0,1.0,Sheffield Utd,3.5,0.7,79.0,31336.0,Kyle Walker,4-2-3-1,Jarred Gillett,Match Report,NaN,Manchester City,2023/2024
3,2023-09-02,15:00,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,2.2,1.4,68.0,52899.0,Kyle Walker,4-2-3-1,Michael Oliver,Match Report,NaN,Manchester City,2023/2024
0,2023-08-11,20:00,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,1.9,0.3,65.0,21572.0,Kevin De Bruyne,4-2-3-1,Craig Pawson,Match Report,NaN,Tottenham Hotspur,2023/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,2023-09-02,15:00,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,2.2,1.4,68.0,52899.0,Kyle Walker,4-2-3-1,Michael Oliver,Match Report,NaN,Luton Town,2023/2024
0,2023-08-11,20:00,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,1.9,0.3,65.0,21572.0,Kevin De Bruyne,4-2-3-1,Craig Pawson,Match Report,NaN,Burnley,2023/2024
1,2023-08-19,20:00,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,1.0,0.3,59.0,NaN,Kyle Walker,4-2-3-1,Robert Jones,Match Report,NaN,Burnley,2023/2024
2,2023-08-27,14:00,Matchweek 3,Sun,Away,W,2.0,1.0,Sheffield Utd,3.5,0.7,79.0,31336.0,Kyle Walker,4-2-3-1,Jarred Gillett,Match Report,NaN,Burnley,2023/2024
3,2023-09-02,15:00,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,2.2,1.4,68.0,52899.0,Kyle Walker,4-2-3-1,Michael Oliver,Match Report,NaN,Burnley,2023/2024

In [581]:
player_stats = pd.read_csv("PL202223Season.csv")

In [582]:
player_stats = player_stats[player_stats['Pos'] !='On matchday squad, but did not play']

In [583]:
player_stats['Pos'] = player_stats['Pos'].str.split(',')

In [584]:
player_stats['Pos']

0               [GK]
1               [GK]
2               [GK]
3               [GK]
4       [LM, AM, FW]
            ...
1342            [CM]
1343            [FW]
1344            [FW]
1347            [CM]
1348            [FW]
Name: Pos, Length: 1180, dtype: object

In [585]:
player_stats = player_stats[['name', 'season',  'Date', 'Day', 'Comp', 'Round', 'Venue', 'Result',
       'Squad', 'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt',
       'Sh', 'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ']]

In [586]:
Midifielders = player_stats[player_stats['Pos'] !="CB"]

In [587]:
#Midfielders = Midfielders[Midfielders['season'] == '2023/2024']

In [588]:
second_df = pd.read_csv('players_2223.csv')
second_df['name'] = second_df['first_name'] + " " + second_df['second_name']

In [589]:
filtered_df2 = second_df[second_df['element_type'] == 'MID']
# Merge the two DataFrames on the 'Player' column
filtered_df2['name'] = filtered_df2['name'].str.strip()
Midfielders['name'] = Midfielders['name'].str.strip()
result_df = Midifielders.merge(filtered_df2, on = 'name', how='left')

In [590]:
Midfielders['name'].unique()

array([], dtype=object)

In [548]:
result_df['name'].unique()

array(['Ederson', 'Julian Alvarez', 'Kyle Walker', 'Erling Haaland',
       'Rodri', 'Mateo Kovacic', 'Phil Foden', 'Manuel Akanji',
       'Nathan Ake', 'Bernardo Silva', 'Josko Gvardiol', 'Jack Grealish',
       'Rico Lewis', 'Jeremy Doku', 'Kevin De Bruyne', 'Sergio Gomez',
       'Cole Palmer', 'Kalvin Phillips', 'Oscar Bobb', 'James Mcatee',
       'Guglielmo Vicario', 'Dejan Kulusevski', 'Yves Bissouma',
       'James Maddison', 'Destiny Udogie', 'Son Heung min', 'Pedro Porro',
       'Richarlison', 'Pape Matar Sarr', 'Emerson', 'Oliver Skipp',
       'Manor Solomon', 'Ivan Perisic', 'Pierre Hojbjerg', 'Ben Davies',
       'Giovani Lo Celso', 'Alisson', 'Andrew Robertson',
       'Dominik Szoboszlai', 'Mohamed Salah', 'Trent Alexander Arnold',
       'Alexis Mac Allister', 'Luis Diaz', 'Cody Gakpo', 'Diogo Jota',
       'Joe Gomez', 'Darwin Nunez', 'Wataru Endo', 'Curtis Jones',
       'Harvey Elliott', 'Ben Doak', 'Kostas Tsimikas', 'Alphonse Areola',
       'Jarrod Bowen', 'Vladimir Coufal', 'Emerson Palmieri',
       'Lucas Paqueta', 'Michail Antonio', 'Said Benrahma',
       'James Ward Prowse', 'Tomas Soucek', 'Edson Alvarez',
       'Pablo Fornals', 'Danny Ings', 'Thilo Kehrer', 'Maxwel Cornet',
       'Kudus Mohammed', 'Aaron Ramsdale', 'Ben White', 'Declan Rice',
       'Bukayo Saka', 'Martin Odegaard', 'Gabriel Martinelli',
       'Kai Havertz', 'Eddie Nketiah', 'Thomas Partey',
       'Takehiro Tomiyasu', 'Oleksandr Zinchenko', 'Jakub Kiwior',
       'Leandro Trossard', 'Jurrien Timber', 'Fabio Vieira', 'Jorginho',
       'Gabriel Jesus', 'Reiss Nelson', 'Pervis Estupinan',
       'Kaoru Mitoma', 'Pascal Gross', 'Solly March', 'Billy Gilmour',
       'James Milner', 'Danny Welbeck', 'Joao Pedro', 'Evan Ferguson',
       'Jason Steele', 'Bart Verbruggen', 'Joel Veltman',
       'Mahmoud Dahoud', 'Julio Cesar Enciso', 'Adam Lallana',
       'Simon Adingra', 'Tariq Lamptey', 'Jordan Ayew', 'Cheick Doucoure',
       'Eberechi Eze', 'Sam Johnstone', 'Jefferson Lerma',
       'Tyrick Mitchell', 'Joel Ward', 'Odsonne Edouard',
       'Jeffrey Schlupp', 'Jean Philippe Mateta', 'Naouirou Ahamada',
       'Jesuran Rak Sakyi', 'Will Hughes', 'Mark Flekken', 'Rico Henry',
       'Bryan Mbeumo', 'Vitaly Janelt', 'Christian Norgaard',
       'Yoane Wissa', 'Aaron Hickey', 'Mathias Jensen', 'Kevin Schade',
       'Kristoffer Ajer', 'Mikkel Damsgaard', 'Keane Lewis Potter',
       'Frank Onyeka', 'Mads Roerslev', 'Shandon Baptiste',
       'Josh Dasilva', 'Michael Olakigbe', 'Morgan Gibbs White',
       'Matt Turner', 'Serge Aurier', 'Danilo', 'Ryan Yates',
       'Taiwo Awoniyi', 'Brennan Johnson', 'Ola Aina', 'Orel Mangala',
       'Neco Williams', 'Anthony Elanga', 'Chris Wood',
       'Cheikhou Kouyate', 'Moussa Niakhate', 'Gonzalo Montiel',
       'Nuno Tavares', 'Boubacar Kamara', 'Ezri Konsa', 'Matty Cash',
       'Lucas Digne', 'John McGinn', 'Ollie Watkins', 'Moussa Diaby',
       'Douglas Luiz', 'Emiliano Martinez', 'Leon Bailey', 'Robin Olsen',
       'Youri Tielemans', 'Nicolo Zaniolo', 'Jhon Duran',
       'Philippe Coutinho', 'Bertrand Traore', 'Cameron Archer',
       'Jaden Philogene Bidace', 'Casemiro', 'Bruno Fernandes',
       'Andre Onana', 'Marcus Rashford', 'Aaron Wan Bissaka', 'Antony',
       'Christian Eriksen', 'Diogo Dalot', 'Luke Shaw', 'Mason Mount',
       'Alejandro Garnacho', 'Anthony Martial', 'Jadon Sancho',
       'Rasmus Hojlund', 'Facundo Pellistri', 'Scott McTominay',
       'Levi Colwill', 'Enzo Fernandez', 'Robert Sanchez',
       'Nicolas Jackson', 'Raheem Sterling', 'Conor Gallagher',
       'Ben Chilwell', 'Malo Gusto', 'Moises Caicedo',
       'Carney Chukwuemeka', 'Reece James', 'Mykhailo Mudryk',
       'Noni Madueke', 'Ian Maatsen', 'Mason Burstow', 'Lesley Ugochukwu',
       'Bernd Leno', 'Antonee Robinson', 'Kenny Tete', 'Harry Wilson',
       'Raul Jimenez', 'Bobby Reid', 'Harrison Reed', 'Andreas Pereira',
       'Sasa Lukic', 'Tom Cairney', 'Joao Palhinha', 'Willian',
       'Luke Harris', 'Adama Traore', 'Aleksandar Mitrovic',
       'Timothy Castagne', 'Rodrigo Muniz', 'Dan Burn', 'Nick Pope',
       'Kieran Trippier', 'Bruno Guimaraes', 'Miguel Almiron',
       'Joelinton', 'Anthony Gordon', 'Sandro Tonali', 'Alexander Isak',
       'Matt Targett', 'Callum Wilson', 'Harvey Barnes', 'Sean Longstaff',
       'Elliot Anderson', 'Valentino Livramento', 'Jacob Murphy',
       'Mario Lemina', 'Pedro Neto', 'Jose Sa', 'Nelson Semedo',
       'Matheus Cunha', 'Joao Gomes', 'Rayan Ait Nouri', 'Fabio Silva',
       'Matheus Nunes', 'Pablo Sarabia', 'Hwang Hee chan', 'Hugo Bueno',
       'Toti Gomes', 'Sasa Kalajdzic', 'Boubacar Traore', 'Milos Kerkez',
       'Neto', 'Dominic Solanke', 'Philip Billing', 'Max Aarons',
       'Ryan Christie', 'Antoine Semenyo', 'Joe Rothwell',
       'Justin Kluivert', 'Jaidon Anthony', 'David Brooks', 'Lewis Cook',
       'Lloyd Kelly', 'Kieffer Moore', 'Hamed Junior Traore',
       'Marcus Tavernier', 'James Hill', 'Wes Foderingham',
       'Oliver Norwood', 'Benie Adama Traore', 'Gustavo Hamer',
       'George Baldock', 'Vinicius Souza', 'William Osula', 'Ben Osborn',
       'Max Lowe', 'Yasser Larouci', 'Chris Basham', 'Oliver McBurnie',
       'Luke Thomas', 'Andre Brooks', 'Jayden Bogle', 'Antwoine Hackford',
       'Anis Ben Slimane', 'Amadou Onana', 'Nathan Patterson',
       'Jordan Pickford', 'Ashley Young', 'Abdoulaye Doucoure',
       'James Garner', 'Idrissa Gana Gueye', 'Arnaut Danjuma',
       'Michael Keane', 'Alex Iwobi', 'Lewis Dobbin', 'Neal Maupay',
       'Beto', 'Dominic Calvert Lewin', 'Youssef Chermiti',
       'Dwight McNeil', 'Thomas Cannon', 'Tyler Onyango',
       'Thomas Kaminski', 'Carlton Morris', 'Marvelous Nakamba',
       'Ryan John Giles', 'Tahith Chong', 'Elijah Adebayo', 'Issa Kabore',
       'Ross Barkley', 'Alfie Doughty', 'Pelly Ruddock Mpanzu',
       'Jacob Brown', 'Chiedozie Ogbene', 'Cauley Woodrow', 'Luke Berry',
       'Josh Cullen', 'Ameen Al Dakhil', 'Connor Roberts',
       'James Trafford', 'Lyle Foster', 'Sander Berge', 'Zeki Amdouni',
       'Luca Koleosho', 'Hannes Delcroix', 'Johann Berg Gudmundsson',
       'Vitinho', 'Benson Manuel', 'Jacob Bruun Larsen', 'Nathan Redmond',
       'Josh Brownhill', 'Anass Zaroury', 'Aaron Ramsey', 'Jack Cork',
       'Jay Rodriguez'], dtype=object)

In [591]:
XGA_stats['Squad'] = XGA_stats['team_name']

In [602]:
result_df = result_df[['name', 'season', 'Date', 'Day', 'Comp', 'Round', 'Venue', 'Result',
       'Squad', 'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt',
       'Sh', 'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'goals_scored',
       'assists', 'total_points', 'minutes', 'goals_conceded', 'creativity',
       'influence', 'threat', 'bonus', 'bps', 'ict_index', 'clean_sheets',
       'red_cards', 'yellow_cards', 'selected_by_percent', 'now_cost',
       'element_type']]

In [636]:
result_df['Round'] = result_df['Round'].str.strip()
result_df['Squad'] = result_df['Squad'].str.strip()
XGA_stats['Round'] = XGA_stats['Round'].str.strip()
XGA_stats['Squad'] = XGA_stats['Squad'].str.strip()



#fbref_data = fbref.drop(['Unnamed: 0'], axis= 'columns') 
print(df2.columns)
print(result_df.columns )
final_data_withXGA = result_df.merge(XGA_stats, how='inner', on =['Round', 'Squad'])

Index(['Date', 'Time', 'Round', 'Day', 'Venue', 'Result', 'GF', 'GA',
       'Opponent', 'xG', 'xGA', 'Poss', 'Attendance', 'Captain', 'Formation',
       'Referee', 'Match Report', 'Notes', 'Squad', 'season'],
      dtype='object')
Index(['name', 'season', 'Date', 'Day', 'Comp', 'Round', 'Venue', 'Result',
       'Squad', 'Opponent', 'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt',
       'Sh', 'SoT', 'CrdY', 'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'goals_scored', 'assists', 'total_points',
       'minutes', 'goals_conceded', 'creativity', 'influence', 'threat',
       'bonus', 'bps', 'ict_index', 'clean_sheets', 'red_cards',
       'yellow_cards', 'selected_by_percent', 'now_cost', 'element_type'],
      dtype='object')

In [639]:
print (final_data_withXGA.isna().sum())

name              0
season_x          0
Date_x            0
Day_x             0
Comp              0
               ...
Referee           0
Match Report      0
Notes           689
team_name         0
season_y          0
Length: 74, dtype: int64

In [640]:
final_data_withXGA.to_csv('couldthisbeit.csv')

In [680]:
test = final_data_withXGA[['name' , 'Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG_x',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'xGA']]

In [681]:
test.columns

Index(['name', 'Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG_x',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'xGA'],
      dtype='object')

In [682]:
test.isna().sum()

name       0
Min        0
Sh         0
SoT        0
Touches    0
Tkl        0
Int        0
Blocks     0
xG_x       0
npxG       0
xAG        0
SCA        0
GCA        0
Cmp        0
Att        0
Cmp%       7
PrgP       0
Carries    0
PrgC       0
Att.1      0
Succ       0
xGA        0
dtype: int64

In [683]:
columns= ['Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG_x',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'xGA'] 
for col in columns:
    test[col] = pd.to_numeric(test[col], errors='coerce')
mean_cpa = test['Cmp%'].mean()
test['Cmp%'].fillna(mean_cpa, inplace=True)

In [684]:
test

,name,Min,Sh,SoT,Touches,Tkl,Int,Blocks,xG_x,npxG,...,GCA,Cmp,Att,Cmp%,PrgP,Carries,PrgC,Att.1,Succ,xGA
0,Ederson,90.0,0.0,0.0,75.0,0.0,0.0,0.0,0.0,0.0,...,0.0,62.0,75.0,82.7,0.0,49.0,0.0,0.0,0.0,0.3
1,Julian Alvarez,90.0,3.0,1.0,53.0,1.0,0.0,1.0,0.3,0.3,...,1.0,36.0,44.0,81.8,2.0,25.0,2.0,0.0,0.0,0.3
2,Kyle Walker,89.0,0.0,0.0,81.0,0.0,0.0,0.0,0.0,0.0,...,1.0,66.0,72.0,91.7,2.0,48.0,1.0,3.0,0.0,0.3
3,Erling Haaland,79.0,4.0,2.0,18.0,0.0,0.0,0.0,0.6,0.6,...,0.0,9.0,11.0,81.8,1.0,15.0,1.0,0.0,0.0,0.3
4,Rodri,90.0,4.0,3.0,122.0,5.0,0.0,0.0,0.5,0.5,...,1.0,107.0,110.0,97.3,4.0,84.0,1.0,0.0,0.0,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684,Johann Berg Gudmundsson,45.0,0.0,0.0,28.0,1.0,1.0,0.0,0.0,0.0,...,0.0,13.0,20.0,65.0,3.0,15.0,2.0,2.0,0.0,1.4
685,Jacob Bruun Larsen,23.0,1.0,0.0,14.0,1.0,0.0,0.0,0.1,0.1,...,0.0,8.0,8.0,100.0,1.0,6.0,3.0,1.0,0.0,1.4
686,Nathan Redmond,31.0,0.0,0.0,8.0,1.0,0.0,0.0,0.0,0.0,...,0.0,4.0,6.0,66.7,0.0,6.0,0.0,0.0,0.0,1.4
687,Josh Brownhill,45.0,3.0,1.0,30.0,1.0,0.0,0.0,0.2,0.2,...,1.0,19.0,25.0,76.0,0.0,15.0,0.0,0.0,0.0,1.4
688,Jack Cork,17.0,0.0,0.0,17.0,1.0,0.0,0.0,0.0,0.0,...,0.0,9.0,16.0,56.3,1.0,12.0,2.0,0.0,0.0,1.4

In [685]:
names = test['name']

In [686]:
test.columns

Index(['name', 'Min', 'Sh', 'SoT', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG_x',
       'npxG', 'xAG', 'SCA', 'GCA', 'Cmp', 'Att', 'Cmp%', 'PrgP', 'Carries',
       'PrgC', 'Att.1', 'Succ', 'xGA'],
      dtype='object')

In [795]:
grouped = test.groupby('name')

In [796]:
grouped = grouped.mean()
#grouped.drop(['name'], inplace = True, axis='columns')

In [797]:
#column_mean = grouped['Cmp%'].mean()
# Fill NaN values in the specific column with the mean
#grouped['Cmp%'].fillna(column_mean, inplace=True)

In [798]:
predictions = regressor.predict(grouped)

In [799]:
grouped['name'] = names 
grouped['xP'] = predictions

In [801]:
grouped[['name', 'xP']].to_csv("MidfieldersPredictedPoints5.csv")

<h1> Filter by actual position </h1>

In [808]:
filtered_df2 = pd.read_csv("AttentionSaleemCleanforMid.csv")
filtered_df2['name'] = filtered_df2['first_name'] +" "+  filtered_df2['second_name']
filtered_df2['name'] = filtered_df2['name'].str.strip() 
points['name'] = points['name'].str.strip()

points  = pd.read_csv("MidfieldersPredictedPoints5.csv")
player_pos_merged = points.merge(filtered_df2, on = 'name')

In [741]:
filtered_df2[filtered_df2['element_type'] =="MID"].to_csv("bruhfuckme2.csv")

In [792]:
#filtered_df2.to_csv("AttentionSaleemCleanForMid.csv")

In [810]:
player_pos_merged [['name', 'xP']].to_csv("MidPredsWootWoot.csv")

In [772]:
points['first_name'] = points['name'].str.split(' ').str[0]

In [777]:
points [points['first_name'] == 'Erling']

             name     xP first_name
0  Erling Haaland  7.668     Erling